# development:
#   adapter: async

# test:
#   adapter: async

# production:
#   adapter: redis
#   url: redis://localhost:6379/1
#   channel_prefix: twitter_clone_production

redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

# development:
#   adapter: async

# test:
#   adapter: async

# production:
#   adapter: redis
#   url: redis://localhost:6379/1
#   channel_prefix: otter_production

development: *redis

test: *redis

production: *redis
